Feature ETP-660: Improve tools
etendosoftware/com.etendoerp.copilot.toolpack pull request #3
Opened 2024-11-08 18:23 UTC by valenvivaldi

2024-11-15 19:02 UTC, fran-roig approved these changes

2024-11-19 14:31 UTC, sebastianbarrozo requested changes

2024-11-19 14:31 UTC, sebastianbarrozo commented on tools/PrintDirectoryTool.py
> +                    if file.endswith(tuple(extensions)):
This is fine, but, endswith is case sensitive ... the file can have uppercase the file extension

2024-11-19 17:55 UTC, sebastianbarrozo approved these changes

2024-11-20 14:45 UTC, merged